paths:
  data: data/citations
  complex: data/citations/collaboration_complex/STARTINGNODE
  laplacians: data/citations/collaboration_complex/STARTINGNODE/laplacians.npy
  boundaries: data/citations/collaboration_complex/STARTINGNODE/boundaries.npy
  citations: data/citations/collaboration_complex/STARTINGNODE/cochains.npy
  input_damaged: data/citations/collaboration_complex/STARTINGNODE/percentage_MISSINGVALUERATIO_input_damaged.npy
  known_values: data/citations/collaboration_complex/STARTINGNODE/percentage_MISSINGVALUERATIO_known_values.npy
  missing_values: data/citations/collaboration_complex/STARTINGNODE/percentage_MISSINGVALUERATIO_missing_values.npy
  simplices: data/citations/collaboration_complex/STARTINGNODE/simplices.npy

data:
  max_simplex_dim: 5
  considered_simplex_dim: 4
  starting_node: small
  missing_value_ratio: 30
  batch_size: 1
  add_component_signal: false
  component_to_add: sol

run_params:
  max_epochs: 700
  gpus: 1
  random_state: 1337
  min_delta: 0.1
  patience: 50

models:
  my_scnn_mlp:
    name: 'my_scnn_mlp'
    learning_rate: 5e-3
    filter_size: 8
    colors: 1
    num_filters: 30
    variance: 0.01
    aggregation: MLP # possible values: 'sum', 'MLP'
    component_to_use: both # possible values: 'both', 'sol', 'irr'
    keep_separated: false

  my_scnn_sum:
    name: 'my_scnn_sum'
    learning_rate: 1e-3
    filter_size: 8
    colors: 1
    num_filters: 30
    variance: 0.01
    aggregation: sum # possible values: 'sum', 'MLP'
    component_to_use: both # possible values: 'both', 'sol', 'irr'
    keep_separated: false

  my_scnn_separated_sum:
    name: 'my_scnn_separated_sum'
    learning_rate: 1e-3
    filter_size: 5
    colors: 1
    num_filters: 30
    variance: 0.01
    aggregation: sum # possible values: 'sum', 'MLP'
    component_to_use: both # possible values: 'both', 'sol', 'irr'
    keep_separated: true

  my_scnn_separated_mlp:
    name: 'my_scnn_separated_mlp'
    learning_rate: 1e-3
    filter_size: 5
    colors: 1
    num_filters: 30
    variance: 0.01
    aggregation: MLP # possible values: 'sum', 'MLP'
    component_to_use: both # possible values: 'both', 'sol', 'irr'
    keep_separated: true

  my_scnn_sol:
    name: 'my_scnn_sol'
    learning_rate: 1e-3
    filter_size: 5
    colors: 1
    num_filters: 30
    variance: 0.01
    aggregation: MLP # possible values: 'sum', 'MLP'
    component_to_use: sol # possible values: 'both', 'sol', 'irr'
    keep_separated: true

  my_scnn_irr:
    name: 'my_scnn_irr'
    learning_rate: 1e-3
    filter_size: 5
    colors: 1
    num_filters: 30
    variance: 0.01
    aggregation: MLP # possible values: 'sum', 'MLP'
    component_to_use: irr # possible values: 'both', 'sol', 'irr'
    keep_separated: true

  deff_scnn:
    name: 'deff_scnn'
    learning_rate: 1e-3
    filter_size: 5
    colors: 1
    num_filters: 30
    variance: 0.01

  deff_scnn_mlp:
    name: 'deff_scnn_mlp'
    learning_rate: 1e-3
    filter_size: 5
    colors: 1
    num_filters: 30
    variance: 0.01
