program: scripts/evaluate_graph_classification.py

command:
  - python3
  - ${program}
  - --config=configs/graph_classification.yml

method: grid

project: TSP-SC-cross-validation
entity: gladia

metric:
  name: val/loss
  goal: minimize

parameters:
  data.fold:
    values:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
