paths:
  data: data/graph-classification
  raw: data/graph-classification/raw

data:
  max_simplex_dim: 2
  considered_simplex_dim: 2
  batch_size: 16
  dataset: REDDITMULTI5K
  fold: 0
  num_folds: 10

run_params:
  max_epochs: 50
  min_epochs: 10
  gpus: 1
  random_state: 1337
  min_delta: 0
  patience: 5

models:
  classification_scnn:
    filter_size: 5
    colors: 3
    aggregation: MLP # possible values: 'sum', 'MLP'
    component_to_use: both # possible values: 'both', 'sol', 'irr'
    keep_separated: false
    readout: mean
    global_nonlinearity: relu
    hidden_size: 64
    dropout_rate: 0.5