paths:
  data: data/graph-classification
  raw: data/graph-classification/raw

data:
  max_simplex_dim: 2
  considered_simplex_dim: 2
  batch_size: 16
  dataset: PROTEINS
  fold: 0
  num_folds: 10
  init_method: mean

run_params:
  max_epochs: 100
  min_epochs: 10
  gpus:
    - 0
  random_state: 1337
  min_delta: 0
  patience: 10

models:
  classification_scnn:
    filter_size: 3
    num_layers: 2
    colors: 3
    aggregation: MLP # possible values: 'sum', 'MLP'
    component_to_use: both # possible values: 'both', 'sol', 'irr'
    keep_separated: false
    readout: mean
    global_nonlinearity: relu
    hidden_size: 64
    dropout_rate: 0.5
    jump_mode: cat
    learning_rate: 0.001
    dim_aggregation: sum
    sched_step_size: 10
    sched_gamma: 0.9
    reduction: sum