program: scripts/evaluate_citations.py


command:
  - python3
  - ${program}
  - --config=configs/citations.yml
  - --starting_node=small

method: grid

project: definitive-sweep

metric:
  name: val/loss
  goal: minimize

parameters:
  models.my_scnn_mlp.filter_size:
    values:
      - 4
      - 8
      - 16

  models.my_scnn_mlp.num_filters:
    values:
      - 16
      - 32
      - 48

  models.my_scnn_mlp.learning_rate:
    values:
      - 1e-3
      - 5e-3
      - 1e-2


